WebApplication2/Controllers/ProjectController.cs
using AdvertisingAgency.Services;
using AdvertisingAgency.Services.Common;
using AdvertisingAgency.Services.Data.Models.ProjectSharing;
using AdvertisingAgency.Services.ProjectSharing;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using AdvertisingAgency.Services.Interfaces;

namespace AdvertisingAgency.Web.Controllers
{
    /// <summary>
    /// Represents a controller for managing project-sharing related operations.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public class ProjectController : BaseController
    {
        private readonly IProjectSharingService _projectSharingService;

        /// <summary>
        /// Initializes a new instance of the ProjectController class with the specified project sharing service.
        /// </summary>
        /// <param name="projectSharingService">The service responsible for project-sharing related operations.</param>
        public ProjectController(IProjectSharingService projectSharingService)
        {
            _projectSharingService = projectSharingService;
        }

        /// <summary>
        /// Shares a project with other users.
        /// </summary>
        /// <param name="model">The view model containing project sharing information.</param>
        /// <returns>The result of the project sharing operation.</returns>
        [HttpPost("share")]
        public async Task<IActionResult> ShareProject([FromForm] SharedProjectViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            try
            {
                await _projectSharingService.ShareProjectAsync(model.CanvasId, userId, model.Thumbnail);
                TempData["SuccessMessage"] = "Project successfully shared!";
                return RedirectToAction(nameof(SharedProjects));
            }
            catch (ProjectSharingService.CustomException ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction(nameof(SharedProjects));
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "An unknown error occurred. Please try again.";
                return RedirectToAction(nameof(SharedProjects));
            }
        }

        /// <summary>
        /// Adds a project to the user's collection.
        /// </summary>
        /// <param name="model">The view model containing project information to add to the collection.</param>
        /// <returns>The result of adding the project to the collection.</returns>
        [HttpPost("add-to-my-collection")]
        public async Task<IActionResult> AddToMyCollection([FromForm] AddToCollectionViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            try
            {
                var success = await _projectSharingService.AddToCollectionAsync(model.CanvasId, userId);
                TempData["SuccessMessage"] = "Project successfully added to your collection!";
                return RedirectToAction("Index", "CanvasMvc");
                
            }
            catch (ProjectSharingService.CustomException ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction(nameof(SharedProjects));
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "An unknown error occurred. Please try again.";
                return RedirectToAction(nameof(SharedProjects));
            }
        }

        /// <summary>
        /// Displays shared projects paginated in the view.
        /// </summary>
        /// <param name="page">The current page number for pagination.</param>
        /// <param name="pageSize">The number of projects per page for pagination.</param>
        /// <returns>The view displaying shared projects.</returns>
        [HttpGet("shared-projects")]
        public async Task<IActionResult> SharedProjects(int page = 1, int pageSize = 12)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var sharedProjects = await _projectSharingService.GetSharedProjectsAsync(userId);

                var paginatedProjects = sharedProjects.Skip((page - 1) * pageSize).Take(pageSize).ToList();
                
                var model = new PaginatedList<SharedProjectViewModel>(paginatedProjects, sharedProjects.Count, page, pageSize);

                return View(model);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Deletes a shared project.
        /// </summary>
        /// <param name="projectId">The unique identifier of the project to delete.</param>
        /// <returns>The result of the project deletion operation.</returns>
        [HttpPost("delete")]
        public async Task<IActionResult> DeleteProject([FromForm] Guid projectId)
        {
            try
            {
                await _projectSharingService.DeleteProjectAsync(projectId);
                TempData["SuccessMessage"] = "Project successfully deleted!";
                return RedirectToAction(nameof(SharedProjects));
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction(nameof(SharedProjects));
            }
        }

        /// <summary>
        /// Displays details of a shared project.
        /// </summary>
        /// <param name="id">The unique identifier of the project to display details for.</param>
        /// <returns>The view displaying details of the shared project.</returns>
        [HttpGet("shared-projects-details")]
        public async Task<IActionResult> Details(Guid? id)
        {
            var viewModel = await _projectSharingService.GetProjectDetails(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }
    }
}

WebApplication2/Controllers/SearchController.cs
using AdvertisingAgency.Data.Data.Models;
using AdvertisingAgency.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AdvertisingAgency.Web.Controllers
{
    /// <summary>
    /// Represents a controller for performing search-related operations.
    /// </summary>
    public class SearchController : BaseController
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISearchService _searchService;

        /// <summary>
        /// Initializes a new instance of the SearchController class with the specified user manager and search service.
        /// </summary>
        /// <param name="userManager">The user manager for managing user-related operations.</param>
        /// <param name="searchService">The service responsible for search-related operations.</param>
        public SearchController(UserManager<ApplicationUser> userManager, ISearchService searchService)
        {
            _userManager = userManager;
            _searchService = searchService;
        }

        /// <summary>
        /// Displays search results for projects.
        /// </summary>
        /// <param name="searchTerm">The search term to look for in projects.</param>
        /// <returns>The view displaying search results for projects.</returns>
        [Authorize(Roles = "Customer")]
        [HttpGet]
        public async Task<IActionResult> Index(string searchTerm)
        {
            try
            {
                var projects = await _searchService.SearchProjectsAsync(searchTerm);
                return View(projects);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Displays search results for users, filtered for administrators.
        /// </summary>
        /// <param name="searchTerm">The search term to look for in users.</param>
        /// <returns>The view displaying search results for users.</returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> UserSearch(string searchTerm)
        {
            try
            {
                var users = await _searchService.SearchUsersAsync(searchTerm);
                var currentUserId = _userManager.GetUserId(User);
                var filteredUsers = users.Where(u => u.Id != currentUserId).ToList();
                return View("~/Views/Users/SearchedUsers.cshtml", filteredUsers);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

WebApplication2/Views/Search/Index.cshtml
@using System.Security.Claims
@using System.Text.RegularExpressions
@using System.Web
@using Microsoft.AspNetCore.Html
@model IEnumerable<ProjectSearchViewModel>

@{
    ViewData["Title"] = "Shared Projects";
    ViewData["BodyClass"] = "canvas-body";
    Layout = "_Layout";
}
<link rel="stylesheet" href="~/MVC CSS_JS/Styles.css">

<style>
    .button-container {
        display: flex;
        justify-content: space-between;
    }

    .btn-fixed-size {
        width: 67px;
        height: 30px;
        white-space: normal;
        white-space: normal;
        font-size: 11px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .modal-content {
        background: rgba(255,255,255,0.8) !important;
        border: none;
    }

    .modal-body {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .modal-dialog {
        max-width: 50% !important;
    }
</style>

<div id="spinner" class="ring" style="z-index: 9999;">
    Loading
    <span></span>
</div>

<div class="background-image-div" style="position:fixed; top:0; left:0; height:100vh; width:100vw; z-index:-1; background-image: url('@Url.Content("~/Images/SearchBackground.gif")'); background-size: cover; background-repeat: no-repeat; background-position: center;"></div>

<div style="display: flex; align-items: center;">
    <h1 style="font-weight: bold; font-family: initial; color: #ffd600; margin: 0;"> 
        @if(Model.Count() > 0)
        {
            <span style="margin-left: 20px; font-size: 20px; font-family: cursive; color: #ffd600;">Search Results:</span>
            <span style="font-size: 40px; font-family: monospace; color: #ffd600;">@Model.Count() projects were found</span>
        }
    </h1>
</div>

    <div class="row">
        @foreach (var project in Model)
        {
            <div class="col-md-3">
                <div class="card mb-2 rounded shadow-sm">
                    <img class="card-img-top" style="cursor:pointer; width:100%; height: auto; margin-left: 6px; margin-top: 6px" src="@project.Thumbnail" alt="Canvas Thumbnail">
                    <div class="card-body">
                        <h5 class="card-title">@project.Name</h5>
                        <p style="font-size: 8px; font-family: cursive">created by @project.Username</p>
                    <p class="card-text">@Html.Encode(GetShortDescription(project.Canvas?.Description))</p>
                        <div>
                            <div class="button-container">
                                <form action="/Project/shared-projects-details" method="get">
                                    <input type="hidden" name="id" value="@project.Id" />
                                    <button type="submit" class="btn btn-primary btn-sm">Details</button>
                                </form>
                                @if (User.FindFirstValue(ClaimTypes.NameIdentifier) != project.UserId.ToString())
                                {
                                    <form action="/Project/add-to-my-collection" method="post">
                                        <input type="hidden" name="CanvasId" value="@project.Id" />
                                        <button type="submit" class="btn btn-success btn-sm">Get It</button>
                                    </form>
                                }
                            </div>
                            <small class="text-muted">Created on @project.CreatedOn.ToString("d MMM yyyy")</small>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

<!-- Modal -->
<div class="modal fade" id="imagePreviewModal" tabindex="-1" aria-labelledby="imagePreviewModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-body d-flex justify-content-center">
                <img id="modalImage" src="" class="img-fluid w-100" />
            </div>
        </div>
    </div>
</div>

@functions {
    public HtmlString GetShortDescription(string description, int maxLength = 29)
    {
        if (string.IsNullOrEmpty(description))
            return new HtmlString("<span class='text-danger'>No description available.</span>");

    // Remove HTML tags
        var regex = new Regex("<.*?>", RegexOptions.Multiline);
        var plainTextDescription = regex.Replace(description, "");

        if (plainTextDescription.Length <= maxLength) return new HtmlString(HttpUtility.HtmlEncode(description));

        var shortDesc = plainTextDescription.Substring(0, maxLength);
        return new HtmlString(HttpUtility.HtmlEncode(shortDesc + "..."));
    }
}

<script src="~/js/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/UsersCss/ScriptsSearch.js"></script>

<script>
    $(document).ready(function () {
        var count = @Model.Count();

        if (count > 0) {
            Swal.fire({
                title: 'Search Results',
                html: `<p>We found ${count} result(s) for your search.</p>`,
                confirmButtonText: 'Okay'
            });
        } else {
            Swal.fire({
                title: 'No Results',
                html: '<p>No results were found.</p>',
                confirmButtonText: 'Go Back'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = '@Url.Action("SharedProjects", "Project")';
                }
            });
        }
    });
</script>

WebApplication2/Views/Search/_PaginationSearchProjects.cshtml
@model PaginatedList<ProjectSearchViewModel>

<div class="pagination">
    @if (Model.HasPreviousPage)
    {
        <a href="@Url.Action("Index", "Search", new { page = Model.PageIndex - 1 })">Previous</a>
    }

    @for (int i = 1; i <= Model.TotalPages; i++)
    {
        if (i == Model.PageIndex)
        {
            <span class="current-page">@i</span>
        }
        else
        {
            <a href="@Url.Action("Index", "Search", new { page = i })">@i</a>
        }
    }

    @if (Model.HasNextPage)
    {
        <a href="@Url.Action("Index", "Search", new { page = Model.PageIndex + 1 })">Next</a>
    }
</div>