WebApplication2/Controllers/CanvasMvcController.cs
using AdvertisingAgency.Data.Data.Models;
using AdvertisingAgency.Services.Interfaces;
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AdvertisingAgency.Web.Controllers
{
    /// <summary>
    /// Represents a controller for managing canvas-related operations using MVC-based views.
    /// </summary>
    public class CanvasMvcController : BaseController
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ICanvasMVCService _canvasService;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly HtmlSanitizer _sanitizer;

        public CanvasMvcController(UserManager<ApplicationUser> userManager, ICanvasMVCService canvasService, IWebHostEnvironment hostingEnvironment, HtmlSanitizer sanitizer)
        {
            _userManager = userManager;
            _canvasService = canvasService;
            _hostingEnvironment = hostingEnvironment;
            _sanitizer = sanitizer;
        }

        /// <summary>
        /// Displays the single page application (SPA) view for canvas.
        /// </summary>
        /// <returns>The view containing canvas-related images.</returns>
        public IActionResult SPAView()
        {
            var decalsDir = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Gallery", "Decals");
            var decalsImages = Directory.EnumerateFiles(decalsDir, "*.svg")
                .Select(Path.GetFileName)
                .ToList();

            var brandsDir = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Gallery", "Brands");
            var brandsImages = Directory.EnumerateFiles(brandsDir)
                .Where(file => file.EndsWith(".png")
                                  || file.EndsWith(".jpg")
                                  || file.EndsWith(".svg")
                                  || file.EndsWith(".bmp")
                                  || file.EndsWith(".gif"))
                .Select(Path.GetFileName)
                .ToList();


            var offroadDir = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Gallery", "Offroad");
            var offroadImages = Directory.EnumerateFiles(offroadDir, "*.svg")
                .Select(Path.GetFileName)
                .ToList();

            var funnyDir = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Gallery", "Funny");
            var funnyImages = Directory.EnumerateFiles(funnyDir, "*.svg")
                .Select(Path.GetFileName)
                .ToList();

            ViewBag.DecalsImageNames = decalsImages.Count > 0 ? decalsImages : null;
            ViewBag.BrandsImageNames = brandsImages.Count > 0 ? brandsImages : null;
            ViewBag.OffroadImageNames = offroadImages.Count > 0 ? offroadImages : null;
            ViewBag.FunnyImageNames = funnyImages.Count > 0 ? funnyImages : null;

            return View();
        }

        /// <summary>
        /// Displays the view for free use of the SPA.
        /// </summary>
        /// <returns>The view containing freely usable canvas-related images.</returns>
        [AllowAnonymous]
        public IActionResult SPA_FreeUse()
        {
            var decalsDir = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Gallery", "Decals");
            var decalsImages = Directory.EnumerateFiles(decalsDir, "*.svg")
                .Select(Path.GetFileName)
                .ToList();

            var brandsDir = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Gallery", "Brands");
            var brandsImages = Directory.EnumerateFiles(brandsDir)
                .Where(file => file.EndsWith(".png")
                               || file.EndsWith(".jpg")
                               || file.EndsWith(".svg")
                               || file.EndsWith(".bmp")
                               || file.EndsWith(".gif"))
                .Select(Path.GetFileName)
                .ToList();


            var offroadDir = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Gallery", "Offroad");
            var offroadImages = Directory.EnumerateFiles(offroadDir, "*.svg")
                .Select(Path.GetFileName)
                .ToList();

            var funnyDir = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Gallery", "Funny");
            var funnyImages = Directory.EnumerateFiles(funnyDir, "*.svg")
                .Select(Path.GetFileName)
                .ToList();

            ViewBag.DecalsImageNames = decalsImages.Count > 0 ? decalsImages : null;
            ViewBag.BrandsImageNames = brandsImages.Count > 0 ? brandsImages : null;
            ViewBag.OffroadImageNames = offroadImages.Count > 0 ? offroadImages : null;
            ViewBag.FunnyImageNames = funnyImages.Count > 0 ? funnyImages : null;

            return View();
        }

        /// <summary>
        /// Displays the index view showing canvas projects.
        /// </summary>
        /// <param name="page">The page number of the projects to display.</param>
        /// <returns>The view containing canvas projects.</returns>
        public async Task<IActionResult> Index(int page = 1)
        {
            int projectsPerPage = 12;

            var user = await _userManager.GetUserAsync(User);

            var projects = await _canvasService.GetCanvasProjects(user, page, projectsPerPage);

            int totalPages = await _canvasService.GetTotalPages(user, projectsPerPage);

            ViewData["CurrentPage"] = page;
            ViewData["TotalPages"] = totalPages;

            return View(projects);
        }

        /// <summary>
        /// Displays the details view for a specific canvas.
        /// </summary>
        /// <param name="id">The unique identifier of the canvas.</param>
        /// <returns>The view containing canvas details.</returns>
        [Route("/canvasmvc/details")]
        public async Task<IActionResult> Details(Guid? id)
        {
            var userId = _userManager.GetUserId(User);
            var viewModel = await _canvasService.GetCanvasDetails(id, userId);

            if (viewModel == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(viewModel);
        }

        /// <summary>
        /// Displays the create view for a new canvas.
        /// </summary>
        /// <returns>The view for creating a new canvas.</returns>
        public IActionResult Create()
        {
            ViewBag.UserId = _userManager.GetUserId(User);
            return View();
        }

        /// <summary>
        /// Handles the creation of a new canvas.
        /// </summary>
        /// <param name="canvas">The canvas data for creation.</param>
        /// <returns>The result of the create operation.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Canvas canvas)
        {
            var user = await _userManager.GetUserAsync(User);

            var result = await _canvasService.CreateCanvas(user, canvas);
            if (!result)
            {
                return BadRequest("Invalid user ID format.");
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Displays the edit view for a specific canvas.
        /// </summary>
        /// <param name="id">The unique identifier of the canvas to edit.</param>
        /// <returns>The view for editing the specified canvas.</returns>
        public async Task<IActionResult> Edit(Guid? id)
        {
            var userId = _userManager.GetUserId(User);
            var canvas = await _canvasService.GetCanvasForEdit(id, userId);

            if (canvas == null)
            {
                return NotFound();
            }

            return View(canvas);
        }

        /// <summary>
        /// Handles the editing of a specific canvas.
        /// </summary>
        /// <param name="id">The unique identifier of the canvas to edit.</param>
        /// <param name="canvas">The updated canvas data.</param>
        /// <returns>The result of the edit operation.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description")] Canvas canvas)
        {
            var userId = _userManager.GetUserId(User);
            var result = await _canvasService.EditCanvas(id, userId, canvas);

            if (!result)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Displays the delete view for a specific canvas.
        /// </summary>
        /// <param name="id">The unique identifier of the canvas to delete.</param>
        /// <returns>The view for confirming the deletion of the specified canvas.</returns>
        public async Task<IActionResult> Delete(Guid? id)
        {
            var userId = _userManager.GetUserId(User);
            var canvas = await _canvasService.GetCanvasForDelete(id, userId);

            if (canvas == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(canvas);
        }

        /// <summary>
        /// Handles the confirmed deletion of a specific canvas.
        /// </summary>
        /// <param name="id">The unique identifier of the canvas to delete.</param>
        /// <returns>The result of the delete operation.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var userId = _userManager.GetUserId(User);
            var result = await _canvasService.DeleteCanvas(id, userId);

            if (!result)
            {
                return NotFound();
            }

WebApplication2/Views/CanvasMvc/Partials/_DeletePartial.cshtml
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const form = document.getElementById('deleteForm');

        form.addEventListener('submit', function (e) {
            e.preventDefault();

            Swal.fire({
                title: 'Are you sure?',
                html: '<img src="@Url.Content("~/Images/ThinkItFace.png")" /> <br/> <p>You won\'t be able to revert this!</p>',
                icon: null, // Set the icon to null
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true,
                showClass: {
                    popup: 'animate__animated animate__fadeInDown'
                },
                hideClass: {
                    popup: 'animate__animated animate__fadeOutUp'
                }
            }).then((result) => {
                if (result.isConfirmed) {
                    // Show the spinner when the user confirms
                    document.getElementById('spinner').style.display = 'block';

                    fetch(form.action, {
                        method: 'POST',
                        body: new FormData(form),
                        headers: {
                            'RequestVerificationToken': document.querySelector('input[name="__RequestVerificationToken"]').value
                        }
                    }).then(function (response) {
                        if (response.ok) {
                            Swal.fire({
                                title: 'Phhh!',
                                html: '<img src="@Url.Content("~/Images/CryingFace.png")" /> <br/> <p>Your project has been deleted!</p>',
                                confirmButtonText: 'Okay',
                                showClass: {
                                    popup: 'animate__animated animate__fadeInDown'
                                },
                                hideClass: {
                                    popup: 'animate__animated animate__fadeOutUp'
                                }
                            }).then(() => {
                                // Reactivate the spinner until the next page loads
                                document.getElementById('spinner').style.display = 'block';
                                window.location.href = '@Url.Action("Index", "CanvasMvc")';
                            });
                        } else {
                            Swal.fire({
                                title: 'Error!',
                                html: '<img src="@Url.Content("~/Images/Ooops.png")" /> <br/> <p>An error occurred while deleting the project.</p>',
                                icon: 'error',
                                confirmButtonText: 'Okay',
                                showClass: {
                                    popup: 'animate__animated animate__fadeInDown'
                                },
                                hideClass: {
                                    popup: 'animate__animated animate__fadeOutUp'
                                }
                            });
                        }
                    }).catch(function () {
                        Swal.fire({
                            title: 'Error!',
                            html: '<img src="@Url.Content("~/Images/Ooops.png")" /> <br/> <p>An error occurred while deleting the project.</p>',
                            icon: 'error',
                            confirmButtonText: 'Okay',
                            showClass: {
                                popup: 'animate__animated animate__fadeInDown'
                            },
                            hideClass: {
                                popup: 'animate__animated animate__fadeOutUp'
                            }
                        });
                    }).finally(() => {
                        // Do not hide the spinner. It will keep running until the next page loads
                    });
                }
            });
        });
    });
</script>

WebApplication2/Views/CanvasMvc/Partials/_DetailsPartial.cshtml
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Hide the spinner when the page loads
        document.getElementById('spinner').style.display = 'none';

        // Add click event listener to the edit buttons
        Array.from(document.getElementsByClassName('edit-link')).forEach(function (editButton) {
            editButton.addEventListener('click', function () {
                document.getElementById('spinner').style.display = 'block'; // Show the spinner
                var projectId = this.getAttribute('data-project-id'); // Get the project id from the button's data-project-id attribute

                // Make a GET request to the Edit action
                fetch('@Url.Action("Edit", "CanvasMvc")' + '?id=' + projectId)
                    .then(function (response) {
                        if (response.ok) {
                            // If the request succeeds, redirect to the Edit page
                            window.location.href = '@Url.Action("Edit", "CanvasMvc")' + '?id=' + projectId;
                        } else {
                            // If the request fails, show an error message
                            if (response.status === 404) {
                                Swal.fire('Error!', 'The project could not be found.', 'error')
                                    .then(function () {
                                        // After showing the error message, redirect to the Index page
                                        window.location.href = '@Url.Action("Index", "CanvasMvc")';
                                    });
                            } else {
                                Swal.fire('Error!', 'An unknown error occurred.', 'error');
                            }
                        }
                    })
                    .finally(function () {
                        document.getElementById('spinner').style.display = 'none'; // Hide the spinner
                    });
            });
        });

        // Add click event listener to the delete buttons
        Array.from(document.getElementsByClassName('delete-link')).forEach(function (deleteButton) {
            deleteButton.addEventListener('click', function () {
                document.getElementById('spinner').style.display = 'block'; // Show the spinner
                var projectId = this.getAttribute('data-project-id'); // Get the project id from the button's data-project-id attribute

                // Show a confirmation dialog
                Swal.fire({
                    title: 'Are you sure?',
                    html: '<img src="@Url.Content("~/Images/ThinkItFace.png")" /> <br/> <p>You won\'t be able to revert this!</p>',
                    icon: null, // Set the icon to null
                    showCancelButton: true,
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: 'No, cancel!',
                    reverseButtons: true,
                    showClass: {
                        popup: 'animate__animated animate__fadeInDown'
                    },
                    hideClass: {
                        popup: 'animate__animated animate__fadeOutUp'
                    }
                }).then((result) => {
                    if (result.isConfirmed) {
                        // If the user confirms, send a DELETE request to the Delete action
                        fetch('@Url.Action("Delete", "CanvasMvc")', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/x-www-form-urlencoded',
                                'RequestVerificationToken': document.querySelector('input[name="__RequestVerificationToken"]').value
                            },
                            body: new URLSearchParams({ id: projectId }).toString()
                        }).then(function (response) {
                            if (response.ok) {
                                // If the request succeeds, show a success message and redirect to the Index page
                                Swal.fire({
                                    title: 'Phhh!',
                                    html: '<img src="@Url.Content("~/Images/CryingFace.png")" /> <br/> <p>Your project has been deleted!</p>',
                                    confirmButtonText: 'Okay',
                                    showClass: {
                                        popup: 'animate__animated animate__fadeInDown'
                                    },
                                    hideClass: {
                                        popup: 'animate__animated animate__fadeOutUp'
                                    }
                                }).then(function () {
                                    window.location.href = '@Url.Action("Index", "CanvasMvc")';
                                });
                            } else {
                                // If the request fails, show an error message
                                Swal.fire({
                                    title: 'Error!',
                                    html: '<img src="@Url.Content("~/Images/Ooops.png")" /> <br/> <p>An error occurred while deleting the project.</p>',
                                    icon: 'error',
                                    confirmButtonText: 'Okay',
                                    showClass: {
                                        popup: 'animate__animated animate__fadeInDown'
                                    },
                                    hideClass: {
                                        popup: 'animate__animated animate__fadeOutUp'
                                    }
                                });
                            }
                        }).finally(function () {
                            document.getElementById('spinner').style.display = 'none'; // Hide the spinner
                        });
                    } else {
                        document.getElementById('spinner').style.display = 'none'; // Hide the spinner
                    }
                });
            });
        });
    });
</script>

WebApplication2/Views/CanvasMvc/Partials/_EditScripts.cshtml
<script>
    tinymce.init({
            selector: 'textarea',
            plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
            toolbar_mode: 'floating',
            init_instance_callback: function (editor) {
                editor.on('keydown', function (e) {
                    const maxLength = 500;
                    const currentLength = editor.contentDocument.body.innerText.length;

                    if (currentLength >= maxLength) {
                        if (e.keyCode != 8) { // Allow to delete characters
                            e.preventDefault();
                            e.stopPropagation();
                        }
                    }

                    document.getElementById('remainingCharacters').textContent = `Remaining characters: ${maxLength - currentLength}`;
                });
            },
        });


    const userId = '@Model.UserId';
    const projectId = document.getElementById('projectId').value;

    function submitEditProject() {
        const projectNameInput = document.getElementById('projectName');
        const projectDescriptionInput = document.getElementById('projectDescription');
        const projectName = projectNameInput.value;
        const projectDescription = tinyMCE.get('projectDescription').getContent();

        if (projectName.length === 0) {
            Swal.fire({
                title: 'Името на проекта не трябва да е празно!',
                showClass: {
                    popup: 'animate__animated animate__fadeInDown'
                },
                hideClass: {
                    popup: 'animate__animated animate__fadeOutUp'
                }
            });
            return false;
        }

        if (projectName.length > 20) {
            Swal.fire({
                title: 'Името на проекта трябва да е най-много 20 символа дълго!',
                showClass: {
                    popup: 'animate__animated animate__fadeInDown'
                },
                hideClass: {
                    popup: 'animate__animated animate__fadeOutUp'
                }
            });
            return false;
        }

        localStorage.setItem('projectName', projectName);
        localStorage.setItem('projectDescription', projectDescription);
        localStorage.setItem('userId', userId);

        // Encode the projectDescription for safe URL usage
        let encodedProjectDescription = encodeURIComponent(projectDescription);

        window.location.href = `/CanvasMVC/SPAView?projectId=${projectId}&projectName=${projectName}&projectDescription=${encodedProjectDescription}&userId=${userId}`;

        return false;
    }

    document.getElementById('projectDescription').addEventListener('input', function (e) {
        const target = e.target;
        const maxLength = target.getAttribute('maxlength');
        const currentLength = target.value.length;

        if (currentLength >= maxLength) {
            return;
        }

        document.getElementById('remainingCharacters').textContent = `Remaining characters: ${maxLength - currentLength}`;
    });

    const textarea = document.getElementById('projectDescription');

    textarea.addEventListener('input', autoResize, false);

    function autoResize() {
        this.style.height = 'auto';
        this.style.height = this.scrollHeight + 'px';
    }
</script>

WebApplication2/Views/CanvasMvc/Partials/_Pagination.cshtml
<div class="pagination">
    @if ((int)ViewData["CurrentPage"] > 1)
    {
        <a href="@Url.Action("Index", new { page = (int)ViewData["CurrentPage"] - 1 })">Previous</a>
    }

    @for (int i = 1; i <= (int)ViewData["TotalPages"]; i++)
    {
        if (i == (int)ViewData["CurrentPage"])
        {
            <span class="current-page">@i</span>
        }
        else
        {
            <a href="@Url.Action("Index", new { page = i })">@i</a>
        }
    }

    @if ((int)ViewData["CurrentPage"] < (int)ViewData["TotalPages"])
    {
        <a href="@Url.Action("Index", new { page = (int)ViewData["CurrentPage"] + 1 })">Next</a>
    }
</div>